- name: Configuring nomad service
  template:
    src: etc/systemd/system/nomad.service.j2
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0664
  become: true
  notify:
    - reload systemd
    - restart nomad

- name: Ensuring nomad service is enabled
  service:
    name: nomad
    enabled: true
  become: true
