platforms:
  - name: debian-9
    groups:
      - nomad_instances
    image: jrei/systemd-debian:9
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
